/**
 * Default permissions for built-in system roles.
 * Used as a fallback in loadCachedAuthUser when a tenant's role
 * was seeded before DEFAULT_ROLES was fully populated (permissions: []).
 */
export const SYSTEM_ROLE_PERMISSIONS: Record<string, string[]> = {
    hq_admin: [
        "dashboard:view",
        "sales:view", "sales:create", "sales:update", "sales:delete", "sales:void", "sales:refund",
        "pos:access", "pos:discount", "pos:void", "pos:credit",
        "products:view", "products:create", "products:update", "products:delete", "products:import",
        "categories:view", "categories:create", "categories:update", "categories:delete",
        "inventory:view", "inventory:create", "inventory:update", "inventory:delete",
        "inventory:transfer", "inventory:adjust", "inventory:stockin", "inventory:stockout",
        "promotions:view", "promotions:create", "promotions:update", "promotions:delete",
        "customers:view", "customers:create", "customers:update", "customers:delete",
        "payments:view", "payments:create", "payments:void", "payments:settle", "payments:manage",
        "documents:view", "documents:create", "documents:update", "documents:delete",
        "reports:view", "reports:sales", "reports:inventory", "reports:financial", "reports:staff",
        "staff:view", "staff:create", "staff:update", "staff:delete",
        "roles:view", "roles:create", "roles:update", "roles:delete",
        "stores:view", "stores:update",
        "branches:view", "branches:update", "branches:create",
        "settings:view", "settings:update",
        "restaurant:view", "restaurant:manage", "tables:create", "tables:update", "tables:delete",
    ],
    hq_manager: [
        "dashboard:view",
        "sales:view", "sales:create", "sales:update", "sales:void",
        "pos:access", "pos:discount", "pos:credit",
        "products:view", "products:create", "products:update", "products:import",
        "categories:view", "categories:create", "categories:update",
        "inventory:view", "inventory:create", "inventory:update",
        "inventory:transfer", "inventory:adjust", "inventory:stockin", "inventory:stockout",
        "promotions:view", "promotions:create", "promotions:update",
        "customers:view", "customers:create", "customers:update",
        "payments:view", "payments:create", "payments:settle", "payments:manage",
        "documents:view", "documents:create", "documents:update",
        "reports:view", "reports:sales", "reports:inventory", "reports:financial", "reports:staff",
        "staff:view", "staff:create", "staff:update",
        "roles:view", "roles:create", "roles:update",
        "stores:view", "stores:update",
        "branches:view", "branches:update",
        "settings:view", "settings:update",
        "restaurant:view", "restaurant:manage", "tables:create", "tables:update",
    ],
    store_owner: [
        "dashboard:view",
        "sales:view", "sales:create", "sales:update", "sales:delete", "sales:void", "sales:refund",
        "pos:access", "pos:discount", "pos:void", "pos:credit",
        "products:view", "products:create", "products:update", "products:delete", "products:import",
        "categories:view", "categories:create", "categories:update", "categories:delete",
        "inventory:view", "inventory:create", "inventory:update", "inventory:delete",
        "inventory:transfer", "inventory:adjust", "inventory:stockin", "inventory:stockout",
        "promotions:view", "promotions:create", "promotions:update", "promotions:delete",
        "customers:view", "customers:create", "customers:update", "customers:delete",
        "payments:view", "payments:create", "payments:void", "payments:settle", "payments:manage",
        "documents:view", "documents:create", "documents:update", "documents:delete",
        "reports:view", "reports:sales", "reports:inventory", "reports:financial", "reports:staff",
        "staff:view", "staff:create", "staff:update", "staff:delete",
        "roles:view", "roles:create", "roles:update", "roles:delete",
        "stores:view", "stores:update",
        "branches:view", "branches:update",
        "settings:view", "settings:update",
        "restaurant:view", "restaurant:manage", "tables:create", "tables:update", "tables:delete",
    ],
    branch_admin: [
        "dashboard:view",
        "sales:view", "sales:create", "sales:update", "pos:access", "pos:discount", "pos:credit",
        "products:view", "products:create", "products:update", "products:import",
        "categories:view", "categories:create", "categories:update",
        "inventory:view", "inventory:create", "inventory:update",
        "inventory:transfer", "inventory:adjust", "inventory:stockin", "inventory:stockout",
        "promotions:view", "promotions:create",
        "customers:view", "customers:create", "customers:update",
        "payments:view", "payments:create", "payments:settle", "payments:manage",
        "documents:view", "documents:create",
        "reports:view", "reports:sales", "reports:inventory",
        "staff:view", "staff:create", "staff:update",
        "roles:view", "roles:create", "roles:update",
        "stores:view", "stores:update",
        "branches:view", "branches:update",
        "settings:view", "settings:update",
        "restaurant:view", "restaurant:manage", "tables:create", "tables:update",
    ],
    store_manager: [
        "dashboard:view",
        "sales:view", "sales:create", "sales:update", "pos:access", "pos:discount", "pos:credit",
        "products:view", "products:create", "products:update", "products:import",
        "categories:view", "categories:create",
        "inventory:view", "inventory:create", "inventory:update", "inventory:stockin", "inventory:stockout",
        "promotions:view", "promotions:create",
        "customers:view", "customers:create", "customers:update",
        "payments:view", "payments:create",
        "documents:view", "documents:create",
        "reports:view", "reports:sales",
        "staff:view", "staff:create", "staff:update",
        "roles:view", "roles:create", "roles:update",
        "settings:view",
    ],
    cashier: [
        "dashboard:view",
        "sales:view", "sales:create", "pos:access",
        "products:view",
        "customers:view",
        "payments:view", "payments:create",
        "documents:view",
    ],
    inventory_staff: [
        "dashboard:view",
        "products:view", "categories:view",
        "inventory:view", "inventory:create", "inventory:update",
        "inventory:adjust", "inventory:transfer", "inventory:stockin", "inventory:stockout",
        "reports:view", "reports:inventory",
    ],
    kitchen_staff: [
        "restaurant:view", "restaurant:manage",
    ],
    waiter: [
        "restaurant:view", "restaurant:manage",
        "tables:view", "tables:create", "tables:update",
        "pos:access",
        "customers:view",
    ],
    staff: [
        "dashboard:view",
        "sales:view", "sales:create", "pos:access",
        "products:view",
        "customers:view",
        "payments:view", "payments:create",
    ],
};
